### ISSUE TITLE
Build out capabilities to hide/show articles based on user's role

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-help#24]
Some articles are only for Org Stewards, Center Stewards, etc.

**Comment by wski** [comment]
Please update all articles in the fake db based on this schema
```
{
        name: 'Getting Started with OZONE',
        file: 'OZONE_overview',
        vide: true,
        role: 0
      },
```

**Comment by bhalt** [comment]
done. You can wire up @wski

**Comment by wski** [comment]
simply use the route `http://localhost:8888/#/1` with the number being the role. if no role is provided a default `0` role will be used signifying a basic user. Keep in mind as discussed there is nothing to stop a user from changing their role to a higher role. But no sensitive information is revealed by doing so.

**Comment by mparizernc** [comment]
How is the user's role passed in to help?

**Comment by jal-vsi** [comment]
Not working in Master or Develop, Help link still takes you to old help items (all 3 (HUD, Center, Webtop) different)

**Comment by wski** [comment]
@mparizernc simply use the route http://localhost:8888/#/1 with the number being the role. if no role is provided a default 0 role will be used signifying a basic user. Keep in mind as discussed there is nothing to stop a user from changing their role to a higher role. But no sensitive information is revealed by doing

**Comment by wski** [comment]
@jal-vsi this still works for me, let's talk tomorrow and make sure this is not a misunderstanding. I'm not sure what you mean for the help links, but this is not implemented into HUD, Center, or Webtop yet and must be accessed directly e.g. `http://ci-xyz.xyz/help`

**Comment by mparizernc** [comment]
I was more talking about how does the application pass in the role.  I got that it works if I pass in the role myself.

**Comment by jal-vsi** [comment]
Passed testing in Latest (Develop) using IE11, FF24, CH36 for User, Org Steward, Admin.  There is no link from HUD/Center/Webtop for this; instead, for testing, replace those names and the rest of the URL with help/#/number (replace number with 0 for User, 1 for Org Steward, 2 for Admin).  e.g. https://ci-latest.amlng.di2e.net:7799/webtop/#/grid/sticky-0/0 replaced with https://ci-latest.amlng.di2e.net:7799/help/#/0 (provides Help for User)

**Comment by tdressel** [comment]
Works on IE, FF and Chrome using Staging using #/0, #/1, and #/2 at the end of URL.
