### ISSUE TITLE
Add video icon to articles that have a video

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-help#34]

**Comment by bhalt** [comment]
@wski Currently there is a video icon in the "unused" folder in ozp-icons, put in "svg" folder and build the icon repo.

video.colors-grayLightest-grayDark.svg

**Comment by bhalt** [comment]
@wski I updated the ozp-icon repo with the video icon. There are several color options available .. can you show me when you implement for me to pick one?

**Comment by wski** [comment]
@bhalt what is the icon name? I'll add it in now

**Comment by bhalt** [comment]
.icon-video-blue @wski

**Comment by jal-vsi** [comment]
All links with a video icon (except "Using Webtop") take you directly to a video.  "Using Webtop" does not take you to a video.  I recommend you add Video Icons to the Related Articles that do have videos (e.g., Add Listings to a Dashboard) and remove the dead sub-link 'Using Webtop'.

**Comment by bhalt** [comment]
@wski "Using Webtop" article is broken. This isn't a video icon issue. Can you fix the article link?

**Comment by wski** [comment]
@bhalt The article is likely broken because of improper formatting in the `.html` files provided by documentation. I can skim over it and see if the formatting issue sticks out.

**Comment by tdressel** [comment]
Passed on staging - Chrome 36 and FF 31

Failed on IE - Sent email to Clark and Soe.  Needs follow up testing on IE.

**Comment by tdressel** [comment]
Also "Using Webtop" link directs to a page but there is no info on it.

**Comment by tdressel** [comment]
Passed on Staging using IE, FF and Chrome.
