### ISSUE TITLE
Related articles show up in a pile

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-help#36]
Related article text is being piled into one `<p>` tag with a giant unusable `<a>` tag. Each article should be separated into it's own `<a>` and `<p>` tags. 

You can see the link result in the bottom of the hover screenshot below.

![image](https://cloud.githubusercontent.com/assets/8047457/9881482/12d060ae-5b9e-11e5-96e7-5cde0c5eb26d.png)

**Comment by wski** [comment]
@clarkjefcoat fixed this

**Comment by jal-vsi** [comment]
Passed testing in both Latest and Release using IE11, FF24, CH36.  Related articles are shown in one row at bottom of help page.

**Comment by tdressel** [comment]
Passed on staging - Chrome 36 and FF 31

Failed on IE - Sent email to Clark and Soe. Needs follow up testing on IE.

**Comment by tdressel** [comment]
Passed on IE on Staging.

**Comment by tdressel** [comment]
Passed on IE on Staging.
