### ISSUE TITLE
"Administration" category heading still shows on homepage even if user's role hides articles inside that category

### ISSUE THREAD

**Issue by bhalt** [ozone-development/ozp-help#39]
Entire category/heading "Administration" should be removed if user role=0

**Comment by jal-vsi** [comment]
Passed testing in Latest (Develop) using IE11, FF24, CH36 for User. The heading "Administration" is not available for User.  There is no link from HUD/Center/Webtop for this; instead, for testing, replace those names and the rest of the URL with help/#/0   e.g. https://ci-latest.amlng.di2e.net:7799/webtop/#/grid/sticky-0/0 replaced with https://ci-latest.amlng.di2e.net:7799/help/#/0

**Comment by tdressel** [comment]
Administration Tab still displays on Staging.

STR-
Pre-Req-
Go to Group Admin page and take away Admin and Org Steward privileges
Go to Apps Mall homepage on staging
Drill into an app
RESULTS - Administration tab displays
EXPECTED RESULTS - Administration tab should NOT display.

**Comment by wski** [comment]
What user are you using? It will only display if your role is above `0`

**Comment by tdressel** [comment]
Administration links did not show for any users.

**Comment by tdressel** [comment]
Sent email on HS.

**Comment by tdressel** [comment]
Tested on staging using IE, FF and Chrome
help/#0 - Did not show Administration section at all
help/#/1 - showed two Org Steward Options
help/#/2 - showed all of the Admin Options
