### ISSUE TITLE
Make video links configurable

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-help#46]
Add variables to a config file so that video links are configurable.

**Comment by wski** [comment]
Waiting for more info from @clarkjefcoat

**Comment by clarkjefcoat** [comment]
The plan is to update OzoneConfig.js to have variables to match our available tutorial videos.  Something like:

```
HELP_VIDEOS': {
       'Toolbar': '/path/to/video',
       'Components': '/path/to/video',
       'Search': '/path/to/video',
       'Rate': '/path/to/video',
       'HUD': '/path/to/video',
       'Webtop': '/path/to/video',
       'Dashboards': '/path/to/video',
       'Submit': '/path/to/video'
   }
```

When deployed the paths to videos can be updated to point to the hosted videos.

**Comment by bhalt** [comment]
can this issue be closed? @wski
