### ISSUE TITLE
Help Menu not displaying Administrator links when redirected back using Home link

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-help#58]
STR-
Log in as Org Steward/Admin
Go to Help
RESULTS - Verify the Administrator links display according to user.
Click on a Help Link (doesn't have to be Administrator link)
Once new link loads, Choose HOME
RESULTS - The Administrator links are missing
EXPECTED RESULTS - The Help links including Administrator links should display like the results previously.

Found on CI-Latest

**Comment by wski** [comment]
fixed
