### ISSUE TITLE
FF HS ONLY - Listing Type and Organizations drop downs cut off the bottom of letters

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-help#69]
STR-
Log onto Apps Mall using FF
RESULTS -  "g and p" in Listing Type and "g" in Organizations drop downs cut off the bottom of letters
EXPECTED RESULTS - Should not cut off.  IE and Chrome are fine.

**Comment by bhalt** [comment]
Reopened this in ozp-center and closing here in order to move this Center issue to the correct repo.
