### ISSUE TITLE
Help Modal - Webtop | Add Listings to a Dashboard | Open Bookmarked Apps screenshot should be darker

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-help#71]
STR-
Go to Webtop | Add Listings to a Dashboard | Open Bookmarked Apps
Screenshot should be darker. It somehow got changed to light.

**Comment by bhalt** [comment]
This is the new light themed modals. Image appears as expected. The goal was to push the light themed modals up with the help articles release, but maybe it didn't make it?
