### ISSUE TITLE
Help Modal - Center | Search for Listings | Screenshot is squished

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-help#74]
STR-
Go to Apps Mall | Help Modal | Center | Search for Listings 
RESULTS - Screenshot is squished
EXPECTED RESULTS - Screen shot should be expanded to reasonable width.

**Comment by tdressel** [comment]
<img width="877" alt="screen shot 2015-12-22 at 2 18 52 pm" src="https://cloud.githubusercontent.com/assets/5015370/11963763/005ed098-a8b7-11e5-9dc1-bbc871194743.png">

**Comment by bhalt** [comment]
That sizing is correct. In comparison, this was the previous squish:
![image](https://cloud.githubusercontent.com/assets/8047457/11963948/3b7ed0d2-a8b8-11e5-9bf6-1704e720dd4c.png)

**Comment by bhalt** [comment]
@tdressel Can this issue be closed?
