### ISSUE TITLE
HUD overview - Remove "Launch" from text and images

### ISSUE THREAD

**Issue by clarkjefcoat** [ozone-development/ozp-help#76]
Update "Understanding HUD" and "HUD groupListings" pages to reflect the changes made for https://github.com/ozone-development/ozp-hud/issues/143

**Comment by clarkjefcoat** [comment]
In addition to the wording changes, we should also update the images.

**Comment by blaino** [comment]
Ah, yes, thanks for that catch. I've gone through all the images in articles/Doc_images and these are the ones I think need to be updated for this ticket (associated with hud #143) and for the tickets that remove (profile) settings from center (center #438) and HUD (hud #142): 

folders_in_HUD_share.png
Main_Menu_drop-down.png
Main_Menu_drop-down_user.png
centerSettingsLink_MainMenu.png
listingManagementLink.png
submit-a-listing.png

Given that there are multiple changes here that need to be consistent across the UI, and some graphics (e.g. the orange circle), perhaps @bhalt would prefer to make the updates?

**Comment by bhalt** [comment]
Stephanie actually did this in a separate branch before she left [branch remove_settings](https://github.com/ozone-development/ozp-help/commits/remove_settings) but it's so far behind master that it's probably easier for me to strip the images out and create a new branch. I can do this @blaino @clarkjefcoat

**Comment by tdressel** [comment]
Passed on Latest

**Comment by tdressel** [comment]
Passed on latest.

**Comment by tdressel** [comment]
Passed on staging.
