### ISSUE TITLE
Help - outdated screen shots display in help modal

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-help#82]
Need to have updated screenshot without Settings option:
Help | Center| Manage Listings you Own
Help | Center| Manage Listings as an Org Steward
Help | Toolbar | Navigate to the Menu
Help | Administration | Manage Listings as a Center Steward
Help | Administration | Change Center Settings
Help | Administration | Manage Center Categories 
Help | Administration | Manage Contact Types
Help | Administration | Manage Intents
Help | Administration | Manage Organizations
Help | Administration | Manage Stewards

Need to have updated screenshot with new portion markings:
Help | Center | Create a Listing

Needs to have updated screenshot without Launch in webtop and Launch in New Tab:
Help | HUD | Using HUD

Remove Open all in new dashboard link:
Home Group Bookmarked Listing by Folder

Replace outdated screenshot( words changed Approve/Reject for <<org>>:
Home | Administration | Approve or Return a Listing as an Org Steward

**Comment by clarkjefcoat** [comment]
@bhalt - Can you look at this issue?

**Comment by bhalt** [comment]
@tdressel Can you take another look at this? I know we did a lot of these (all the Settings removal especially) before -- and when checking ci-latest now, the only one I found not done was portion markings. I made that change. Let me know if anything in here is still missing (I may have misunderstood the last wording change as well for Approve/Reject). Thanks!

**Comment by tdressel** [comment]
Yep all looks updated.
