### ISSUE TITLE
Listing Resources | Tour Ends abruptly

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-help#84]
STR-
Go to Take the Tour
Navigate to Listing Resources 
RESULTS - The Next button is grayed out but it's hard to tell.  When I choose > arrow it just ends the tour.  The user is sort of lost at that moment like "what just happened?"
EXPECTED RESULTS - Remove the NEXT button so the user knows it is the END of the Tour.

**Comment by clarkjefcoat** [comment]
I believe this was fixed in https://github.com/ozone-development/ozp-center/pull/611

Please retest.

**Comment by tdressel** [comment]
Button is removed.

**Comment by tdressel** [comment]
NEXT Button is removed from staging.
