### ISSUE TITLE
Tour - Listing Tiles to Listing Overview is too slow in Chrome and broke in FF31

### ISSUE THREAD

**Issue by tdressel** [ozone-development/ozp-help#85]
STR-
Go to Take the Tour
Navigate to Listing Tiles
Advance to Next Step in tour - Listing Overview
RESULTS - Chrome it is so slow it loads the pop up detail and takes forever to load the tour overlay.  FF is just broke altogether.
EXPECTED RESULTS - Chrome should load overlay faster so it doesn't cause confusion to user.  FF should show the Listing Overview Tile.

**Comment by clarkjefcoat** [comment]
I believe this was fixed in ozone-development/ozp-center#611

Please retest. @tdressel

**Comment by tdressel** [comment]
Passed on latest. It wasn't as slow.

**Comment by tdressel** [comment]
This passed but new bug coming through.
